[package]
name = "example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lollipop = { path = ".." }
wasm-bindgen = "0.2.8"
js-sys = "0.3.6"
web-sys = "0.3.6"
